import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container": "#e5eeff",
        "secondary-container": "#82f5c1",
        "tertiary-fixed-dim": "#c5c7c8",
        "on-tertiary-fixed-variant": "#454748",
        "tertiary-container": "#26292a",
        outline: "#75777d",
        "outline-variant": "#c5c6cd",
        "inverse-surface": "#213145",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed-variant": "#005137",
        "secondary-fixed": "#85f8c4",
        "on-secondary-fixed": "#002114",
        secondary: "#006c4a",
        "on-tertiary-fixed": "#191c1d",
        "surface-bright": "#f8f9ff",
        error: "#ba1a1a",
        "on-tertiary-container": "#8e9091",
        "on-error": "#ffffff",
        "inverse-on-surface": "#eaf1ff",
        "on-primary-fixed": "#111c2d",
        "on-background": "#0b1c30",
        "on-error-container": "#93000a",
        "on-primary": "#ffffff",
        surface: "#f8f9ff",
        "on-surface-variant": "#45474c",
        "primary-container": "#1e293b",
        "on-primary-fixed-variant": "#3c475a",
        "primary-fixed-dim": "#bcc7de",
        "on-secondary": "#ffffff",
        "on-primary-container": "#8590a6",
        background: "#F8F9FA",
        "on-surface": "#0b1c30",
        "on-tertiary": "#ffffff",
        "surface-container-highest": "#d3e4fe",
        tertiary: "#121516",
        "on-secondary-container": "#00714e",
        "surface-container-high": "#dce9ff",
        "secondary-fixed-dim": "#68dba9",
        "primary-fixed": "#d8e3fb",
        "surface-container-low": "#eff4ff",
        "surface-tint": "#545f73",
        "inverse-primary": "#bcc7de",
        primary: "#091426",
        "surface-dim": "#cbdbf5",
        "tertiary-fixed": "#e1e3e4",
        "error-container": "#ffdad6",
        "surface-variant": "#d3e4fe",
      },
      spacing: {
        "margin-mobile": "16px",
        "margin-desktop": "48px",
        gutter: "24px",
        "stack-sm": "8px",
        "container-max": "1280px",
        "stack-lg": "32px",
        "stack-md": "16px",
      },
      fontFamily: {
        "headline-lg-mobile": ["var(--font-jakarta)"],
        "label-md": ["var(--font-inter)"],
        "label-sm": ["var(--font-inter)"],
        "display-lg": ["var(--font-jakarta)"],
        "headline-md": ["var(--font-jakarta)"],
        "body-md": ["var(--font-inter)"],
        "headline-lg": ["var(--font-jakarta)"],
        "body-lg": ["var(--font-inter)"],
      },
    },
  },
  plugins: [],
};

export default config;
